trigger:
  branches:
    include:
      - main

pool:
  name: Default  # This tells Azure to use your own VM

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: build
    Dockerfile: '**/Dockerfile'
    tags: |
      mini-project5:$(Build.BuildId)
