trigger:
  branches:
    include:
      - main

pool:
  name: Default  # Your self-hosted agent pool

steps:

# Step 1: Checkout code
- task: Checkout@1

# Step 2: Install Node.js
- task: UseNode@1
  inputs:
    version: '18.x'

# Step 3: Install NPM dependencies
- script: |
    npm install
  displayName: 'Install dependencies'

# Step 4: Build Docker image
- task: Docker@2
  inputs:
    containerRegistry: 'MyDockerRegistry' # Optional if pushing to registry
    repository: 'myapp'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)

# Step 5: SSH Deploy (Optional, only if needed)
# - task: SSH@0
#   inputs:
#     sshEndpoint: 'MySSHConnection'
#     runOptions: 'commands'
#     commands: |
#       docker run -d -p 3000:3000 myapp:$(Build.BuildId)
#     failOnStdErr: true
